ckanext/unaids/theme/templates/organization/read_base.html
=> ADX-327 Adding harvest sources link in organisation overview.

ckanext/unaids/fanstatic/autocomplete-without-creating-new-options.js, ckanext/unaids/presets.json, ckanext/unaids/theme/templates/base.html, ckanext/unaids/theme/templates/organization/member_new.html
- This is a git reshuffle of https://github.com/fjelltopp/ckanext-unaids/pull/67
- Nothing has changed since moving it
- Thanks @tomeksabala for helping sort out the git stuff
=> ADX-394 Force users to select an autocomplete value

ckanext/unaids/theme/public/custom.css, ckanext/unaids/theme/templates/home/layout1.html
Mary and Ian have asked for a minor change to the Home Page...
=> ADX-487 Minor adjustment to homepage.

ckanext/unaids/theme/templates/package/snippets/resource_item.html
=> ADX-517 Fixing missing last modified description of a resource.

ckanext/unaids/react/components/FileInputComponent/src/FileUploader.js
This was a bad copy/paste from the bulk file uploader where `handleNetworkError` was never defined in this file
=> fix-handleNetworkError-undefined

ckanext/unaids/assets/BulkFileUploaderComponent.css, ckanext/unaids/blueprints/unaids_blueprint.py, ckanext/unaids/react/components/BulkFileUploaderComponent/index.js, ckanext/unaids/react/components/BulkFileUploaderComponent/index.test.js, ckanext/unaids/react/components/BulkFileUploaderComponent/src/ModalBody.js, ckanext/unaids/theme/templates/scheming/package/read.html
https://fjelltopp.atlassian.net/browse/ADX-724
=> ADX-724 resource type selector in BulkFileUploader

ckanext/unaids/theme/templates/home/layout1.html, ckanext/unaids/theme/templates/snippets/dataset_selector.html
We need to add the new dataset to the dataset selector and update the button on the home page.
=> ADX-733 New country estimates dataset.

ckanext/unaids/theme/public/custom.css, ckanext/unaids/theme/templates/home/layout1.html, ckanext/unaids/theme/templates/package/read_base.html
This was a request from Mary, to be merged by Monday if possible.
At the moment links are just pointing to Navigator production, how easy is it to point to Navigator staging from ADR staging and Navigator production from ADR production?
If it will delay us merging on Monday, I suggest we merge deploy on Monday and open a separate ticket for the staging/production split.
=> ADX-775  Adds some links to the Navigator into the ADR. 

ckanext/unaids/react/components/BulkFileUploaderComponent/src/ModalBody.js
- https://fjelltopp.atlassian.net/browse/ADX-767
- Video showing fix: https://youtu.be/SyfIjIxEH0c
=> ADX-767-fix-upload-button-not-being-disabled

ckanext/unaids/blueprints/unaids_dataset_transfer.py, ckanext/unaids/tests/test_dataset_transfer.py
https://fjelltopp.atlassian.net/browse/ADX-749
=> ADX-749-datasettransfer-not-working-for-collaborator

ckanext/unaids/assets/custom.css, ckanext/unaids/theme/templates/home/layout1.html
https://fjelltopp.atlassian.net/browse/ADX-812
No changes have been made
The word cloud is 25% smaller
The word cloud is 50% smaller
=> ADX-812-mobile-friendly-unaids-wordcloud

ckanext/unaids/assets/map_selector.js
Copy of https://github.com/fjelltopp/ckanext-unaids/pull/202
=> remove-unnecessary-console-log

ckanext/unaids/helpers.py, ckanext/unaids/plugin.py, ckanext/unaids/theme/templates/base.html, ckanext/unaids/theme/templates/header.html
- https://fjelltopp.atlassian.net/browse/ADX-411
- https://github.com/fjelltopp/adx_develop/pull/96
=> ADX-411-add-google-analytics

.github/workflows/test.yml, ckanext/unaids/react/jest/globals.js, ckanext/unaids/react/package.json, ckanext/unaids/react/yarn.lock
https://fjelltopp.atlassian.net/browse/ADX-819
```
$ yarn audit
173 vulnerabilities found - Packages audited: 1781
Severity: 2 Low | 131 Moderate | 24 High | 16 Critical
Done in 2.83s.
```
```
$ yarn audit
yarn audit v1.22.17
warning package.json: No license field
warning No license field
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Inefficient Regular Expression Complexity in nth-check       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ nth-check                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.0.1                                                      │ …
```
=> ADX-819-fix-yarn-security-vulnerabilities

ckanext/unaids/assets/custom.css, ckanext/unaids/theme/templates/base.html, ckanext/unaids/theme/templates/recline_view.html
https://fjelltopp.atlassian.net/browse/ADX-810
=> ADX-810-cleanup-datapreview-css

ckanext/unaids/blueprints/svg_map_options.py
=> Missing py3 compatibilites

ckanext/unaids/theme/templates/base.html
Reverts fjelltopp/ckanext-unaids#219
https://fjelltopp.atlassian.net/browse/ADX-840
=> ADX-840 Revert "ADX-815 Remove default CKAN css"

ckanext/unaids/theme/templates/home/layout1.html, ckanext/unaids/theme/templates/snippets/dataset_selector.html
Some simple small changes to CKAN templates to be merged once we have merged: https://github.com/fjelltopp/unaids_data_specifications/pull/52
=> ADX-842 Template changes for new estimates round

ckanext/unaids/assets/FileInputComponent.css, ckanext/unaids/react/components/FileInputComponent/src/ResourceForker.js
Turns out these were quite easy to fix:
1) the current resource is now greyed out with a no-go icon rather than removed by filtering - this prevent odd search results when the only matching resource is self
2) `synchroniseResourceAndMetadata()` now works correctly. Actually, it worked just by uncommenting the code so... I am not sure what was going on Friday except I cleared all dirty changes across my ADR this morning so it may have been some local change
=> ADX-885 ADX-886 resource forking UI fixes

ckanext/unaids/theme/templates/package/resource_read.html
=> ADX-887 fix resource_read access issue

ckanext/unaids/i18n/fr/LC_MESSAGES/ckanext-unaids.po
Translations in po file for CKAN-UNAIDS
=> Translate latest po file for fr

ckanext/unaids/theme/templates/organization/bulk_process.html
Fix the error at **ADR/organization/bulk_process/<organisation_name>**.
By adding a block in file ckanext/unaids/templates/organization/bulk_process.html
=> Fix the "Manage Datasets" Page
