- ckanext/unaids/validation_table_schemas/inputs_unaids_anc.json
- ckanext/unaids/validation_table_schemas/inputs_unaids_art.json
- ckanext/unaids/validation_table_schemas/inputs_unaids_population.json
- ckanext/unaids/validation_table_schemas/inputs_unaids_survey.json
This implements small edits to the Naomi input table schemes:
* Adds ASFR column to population dataset. Perhaps this is preferred as a different table though?
* Renames `ancrt_*` to `anc_*`.
* Renames `current_art` to `art_current`.
* Adds `art_new` field.
> Input schema edits

- ckanext/unaids/theme/templates/snippets/dataset_selector.html
Ian wants a direct link to a general dataset pre-populated with some fields for VMMC data.
Do we have any issues with this.  It breaks the model of the dateset selector slightly, but I can't see any practical problems with it other than language translation.
> Add a VMMC link in the data set selector.

- ckanext/unaids/theme/public/unaids.css
- ckanext/unaids/theme/templates/base.html
- We lost our custom UNAIDS styles when upgrading to ckan 2.9
- The order in which the base css file has moved lower down in the htm, so we need to shuffle our custom css imports lower down in the order to overwrite the base css
- This was technically always an issue which wasn't causing any ugly effects, so it went unnoticed 😅
> Fix missing colors from unaids theme

- ckanext/unaids/fanstatic/webassets.yml
- ckanext/unaids/theme/templates/base.html
- ckanext/unaids/theme/templates/package/read.html
- ckanext/unaids/theme/templates/scheming/form_snippets/text_template.html
- As per the [python3 migrate guide](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#web-assets-js-and-css), we need move over to using `webassets.yml` as it has a smarter way of grouping imports of css/js files
- I'll migrate over the scripts sitting in `/fanstatic` directory
- Implemented `webassets.yml` and updated all references where we want to import the files
> migrated scripts to webassets

- ckanext/unaids/plugin.py
- setup.py
The recline_view creates the "Data Explorer" in ckan that lets you browse, filter and graph data. 
However, changing which files get an autocreated recline view requires a hard code change.  I think i will open up a PR with core ckan to change this to a config change. 
In the meantime I have this pretty neat fix which involves creating a new unaids specific recline view from the same base as the orgiinal recline view.  This unaids recline view can then be edited as desired.  
As this is a plugin shipped by default with ckan core, it can't be overridden by the usual git clone/edit/install route, and the extending the reclineview base works well.
This is linked to https://github.com/fjelltopp/adx_develop/pull/18, and https://github.com/fjelltopp/adx_deploy/pull/52
> ADX-417 Autogenerate Data Explorers for geojson files

- ckanext/unaids/plugin.py
- The `organizations` filter in the sidebar & pill under the search bar are only single-select however we say `organizations` instead of simply `organization`
- Note that `Tags` are correctly named as you can select multiple
- Change `organizations` to `organization`
> Changed organization filter to singular

- ckanext/unaids/plugin.py
This uses the new IDataValidation interface to only validate data that has a schema field specified, and to trigger asyncronous whole-package validation if the "validate_package" field is present.
> ADX-463 Fix validation logic.

- ckanext/unaids/theme/templates/package/collaborators/collaborator_new.html
This just touches up a template for the new Collaborators feature.  The feature seems to work well and will be really valuable I think moving forwards.  
There is possible overlap with ckanext-restricted here.  However, adding a collboarator to the package under the role (member) is effectively shorthand for going through adding an individual user to every seperate resource. 
A possible hole in this feature is that it would be nice to add another org as a collaborator so that all users of the orgs can contribute to the dataset.  But something to consider for the mid to long-term future I think.  
Related to: https://github.com/fjelltopp/adx_develop/pull/24
> ADX-284 Clean up the new collaborator form.

- ckanext/unaids/theme/public/custom.css
- Website footer floats in the middle of the page when there's little content to display
- Set up a sticky footer
- See https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/
> Adx 464 make footer sticky

- ckanext/unaids/theme/templates/snippets/changes/resource_extras.html
- The ckan `/snippets/changes/resource_extras.html` was not correctly handling ascii errors
- It's due to `resource_name` having non ascii characters and then being placed within a `str.format()`
- When we have a dataset called `Côte d'Ivoire Inputs UNAIDS Estimates 2021`, create a dataset with resources, clicking the `Changes` button on the Activity Stream would cause a server error
- A server error was reporting `'ascii' codec can't encode character u'\xf4'`
- Allow jinja2 to render the link tags itself, rather than python string formatting inline in the template
- Remove duplicate code by creating jinja2 macros
See git diff of the changes i've made from the original ckan template here:
https://gist.github.com/Manoj-nathwani/cc31d1294eceb83654dfcefccf3cefc1/revisions
See video here …
> ADX-494-fix-ascii-errors-on-resource-extreas-snippet

- ckanext/unaids/dataset_transfer/logic.py
- ckanext/unaids/tests/test_dataset_transfer.py
Attempting to transfer a dataset with ascii characters causes an error
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf4' in position 1: ordinal not in range(128)
File "flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "flask/views.py", line 89, in view
return self.dispatch_request(*args, **kwargs)
File "flask/views.py", line 163, in dispatch_request
return meth(*args, **kwargs)
File "py", line 734, in post
pkg_dict = get_action(u'package_update')(context, data_dict)
File "ckan/logic/__init__.py", line 473, in wrapped
result = _action(context, data_dict, **kw)
File "ckan/logic/action/update.py", line 330, in package_update …
```
> Adx 571 fix dataset-transfer ascii errors

- ckanext/unaids/react/components/BulkFileUploaderComponent/index.test.js
- ckanext/unaids/react/components/BulkFileUploaderComponent/src/App.js
https://fjelltopp.atlassian.net/jira/software/projects/ADX/boards/4?selectedIssue=ADX-647
- We were requesting the authz token before uploading any files, then recycling the same token for every file upload
- The issue is that if a user uploads 20 files, each taking 2mins to upload, then the last few files would fail to upload as the auth token would have expired
- We now request a new auth token before uploading each file
> Adx 648 request authz token before each bulked file upload

- ckanext/unaids/react/components/BulkFileUploaderComponent/src/App.js
- ckanext/unaids/react/components/FileInputComponent/index.test.js
- ckanext/unaids/react/components/FileInputComponent/src/App.js
- ckanext/unaids/react/components/FileInputComponent/src/FileUploader.js
https://fjelltopp.atlassian.net/jira/software/projects/ADX/boards/4?selectedIssue=ADX-647
- We were requesting the authz token on page load
- This meant if you open the file upload page, leave it open for 30mins, the token would expire when you finally got around to selecting a file to upload
- We now request a new auth token at the time of actually uploading something
> get-authz-token-before-file-upload

- ckanext/unaids/react/components/BulkFileUploaderComponent/src/App.js
Before all files have finished uploading, we wrongly state Uploads Complete
Now we correctly show it's still uploading
Then once completed, it says Uploads Complete
> fix-uploads-completed-timing

- ckanext/unaids/theme/templates/package/snippets/resource_item.html
The `Delete` button has gone missing on the dataset_show page
Originally `ckanext-file_uploader_ui` was adding the `Delete` button to `resource_item_explore_links`
I've copied the `<li>` from here: https://github.com/fjelltopp/ckanext-file_uploader_ui/blob/development/ckanext/file_uploader_ui/templates/package/snippets/resource_item.html#L37-L44
> add delete resource button to dataset_show

- ckanext/unaids/plugin.py
- ckanext/unaids/tests/test_giftless_backend.py
- requirements.txt
- test.ini
By implementing IResourceController interface this PR enhances resource create/update decorator which upload file to giftless storage and updates blob storage fields in the resource dict.
Notes:
1. Due to an issue in ckanext_blob_storage & ckanext_authz service this PR uses HTTP to get giftless auth token. The root cause issue should be resolved soon with: https://github.com/datopian/ckanext-authz-service/pull/25
2. This PR lacks integration pytests as it'll be much easier to write them once 1. is resolved
> Adx 641 giftless ckan actions

- ckanext/unaids/react/components/BulkFileUploaderComponent/index.js
- ckanext/unaids/react/components/BulkFileUploaderComponent/index.test.js
- ckanext/unaids/react/components/BulkFileUploaderComponent/src/App.js
- ckanext/unaids/react/components/FileInputComponent/index.js
- ckanext/unaids/react/components/FileInputComponent/index.test.js
- ckanext/unaids/react/components/FileInputComponent/src/App.js
- ckanext/unaids/react/components/FileInputComponent/src/FileUploader.js
- ckanext/unaids/theme/templates/package/snippets/bulk_file_uploader.html
- ckanext/unaids/theme/templates/scheming/form_snippets/upload.html
Card: https://fjelltopp.atlassian.net/browse/ADX-665
- Here's how far I got with trying to get tests working with this feature
- The issue is that I was getting a 404 when attempting a GET on resource.new
- I'm leaving this for now after sinking in a few hours of work
```
import pytest
import ckantoolkit
from bs4 import BeautifulSoup
from ckan.tests import factories
from ckan.lib.helpers import url_for
@pytest.mark.usefixtures("clean_db", "with_request_context")
class TestGiftlessFrontEnd(object):
def test_giftless_resource_create(self, app):
user = factories.User()
dataset = factories.Dataset(
type="test-schema",
)
url = '{}/{}/resource/new'.format(
dataset["type"], dataset["name"]
)
response = app.get(
url=url,
extra_environ={"REMOTE_USER": user["name"]},
status=200
)
soup = …
```
> ADX-665-fix-resource-create-restricted-error

- ckanext/unaids/theme/templates/scheming/form_snippets/upload.html
- The single file uploader takes a few seconds to load as it's waiting for ckan.i18n to load into the browser
- It's confusing to users as they expect everything to be loaded onto the page immediately.
- Added a simple loading banner as a placeholder until the react component is rendered
Uploading a new file/url
|loading |rendered|
--- | --- 
|![image](https://user-images.githubusercontent.com/2634482/118276400-85b64400-b4bf-11eb-9ba0-5fc77abace96.png)|![image](https://user-images.githubusercontent.com/2634482/118276489-a088b880-b4bf-11eb-9a15-7895effd4b70.png)|
Editing an existing file/url
|loading |rendered|
--- | --- 
|![image](https://user-images.githubusercontent.com/2634482/118276821-fc534180-b4bf-11eb-8626-8039812a7f8b.png)|![image](https://user-images.githubusercontent.com/2634482/ …
> Nicer loading for single file uploader

- ckanext/unaids/react/components/FileInputComponent/index.js
- ckanext/unaids/react/components/FileInputComponent/src/App.js
- ckanext/unaids/theme/templates/scheming/form_snippets/upload.html
- The react single file uploader renders content before all states have been updated
- This causes the url field to display regardless if there's already a url/file set which causes an odd lag effect
- You can see it here: https://youtu.be/3mAPjIpSd1g
- We're now reading the raw html sitting inside the component pre-render and storing it. We then display it until the UseEffect has completed running and all states have been updated.
> smoother react component loading flow

- ckanext/unaids/i18n/extra_translations.py
- ckanext/unaids/presets.json
- ckanext/unaids/theme/templates/organization/member_new.html
- ckanext/unaids/theme/templates/package/collaborators/collaborator_new.html
This change accompanies the PR for ADX-658 in ckanext-emailasusername. 
It makes some small changes to the UI so that the placeholder of user search inputs indicates that you can search by email. 
For instance the restricted fields of a resource...
Have I missed any other places in the UI where people commonly search for users?
> Adx 658 email user search

- ckanext/unaids/theme/templates/package/resource_read.html
This PR enables the old data files download from the system by enabling `activity_id` query arg supported by `ckanext-blob-storage`
> Adx 672 activity id download

- ckanext/unaids/theme/public/custom.css
- ckanext/unaids/theme/templates/package/read_base.html
- ckanext/unaids/theme/templates/package/releases/list.html
[Jira ticket ADX-715](https://fjelltopp.atlassian.net/jira/software/projects/ADX/boards/4?selectedIssue=ADX-715)
▶️ [View video of responsiveness](https://youtu.be/CzaulymHjx0)
| before     | after    |
|-------|-----------------------|
| ![image](https://user-images.githubusercontent.com/2634482/123825996-48830580-d8f7-11eb-8a4b-91d6cfb7d1a5.png) | ![image](https://user-images.githubusercontent.com/2634482/123826035-4faa1380-d8f7-11eb-8cf2-0d8524cf7f57.png)
| ![image](https://user-images.githubusercontent.com/2634482/123823377-0a84e200-d8f5-11eb-835e-9d79cca800fb.png) | ![image](https://user-images.githubusercontent.com/2634482/123823398-0f499600-d8f5-11eb-8662-66b92996c2f0.png) |
I tried replacing the `<u>` with a `<b>` however we don't seem to support bold with the font we're using …
> ADX-715 dataset releases frontend updates

- ckanext/unaids/react/components/FileInputComponent/index.test.js
- ckanext/unaids/react/components/FileInputComponent/src/App.js
- After uploading a new resource. Go into manage to edit it and change the description.
- The uploaded file will now disappear and the filename will be set to `__`
- We were forgetting to set the hidden `url` <input> field when editing a resource which already had a file uploaded to it.
- This was missed as it's easy to confuse the fields for what they mean. The `url` <input> needs to be set to the filename if the resource is a file upload. This isn't super intuitive however it's what the ckan form expects. If the resource is a url, then the url field is however set to a full url 😅 
Interestingly, we've never attempted to fix this in the past either:
https://github.com/fjelltopp/ckanext-unaids/commits/development/ckanext/unaids/react/components/FileInputComponent/src/App.js
> ADX-718 Fixed __ filename error

- ckanext/unaids/plugin.py
- ckanext/unaids/react/components/FileInputComponent/index.test.js
- ckanext/unaids/react/components/FileInputComponent/src/App.js
- ckanext/unaids/tests/test_plugin.py
- When uploading urls/files through the single or bulk file uploaders, we are never setting the `last_updated` field on the resource
- Using `before_create` and `before_update` set `last_updated` to a timestamp if (and only if) a change has been made to the file or url fields which involves tracking `['url_type', 'lfs_prefix', 'sha256', 'size', 'url']` for any changes.
- The react single file uploader has also been updated to us the `existingResourceData.url` in the resource `url` field, rather than `fileName`.
> ADX-717 fix last updated on resource uploads

- ckanext/unaids/assets/BulkFileUploaderComponent.css
- ckanext/unaids/react/components/BulkFileUploaderComponent/index.js
- ckanext/unaids/react/components/BulkFileUploaderComponent/index.test.js
- ckanext/unaids/react/components/BulkFileUploaderComponent/src/App.js
- ckanext/unaids/react/components/BulkFileUploaderComponent/src/FileUploader.js
- ckanext/unaids/react/components/BulkFileUploaderComponent/src/Modal.js
- ckanext/unaids/react/components/BulkFileUploaderComponent/src/ModalBody.js
- ckanext/unaids/react/jest/globals.js
- ckanext/unaids/tests/test_dataset_transfer.py
- ckanext/unaids/theme/templates/package/snippets/bulk_file_uploader.html
- ckanext/unaids/theme/templates/scheming/package/read.html
The bulk file uploader was only accessible via the sidebar | A modal would then allow you to select files to upload as new resources
--- | ---
You can now directly drag-and-drop files onto the page
|With schema |Without schema 
--- | ---
This will then open the modal just like before with your files selected.
- Added new dropzone above resources section of page
- Slightly nicer css on-hover in existing modal dropzone
- Nothing else has changed, there's just been a lot of code reorganising
> ADX-721 add fullpage bulk file uploader

- ckanext/unaids/helpers.py
This is a hotfix for ADX-730.  The issue is a minor issue that only appears when users are trying to edit private datasets that don't have activity streams.  These are a very small minority of datasets either created by someone with the API or created so long ago before the UI removed the public/private setting.
There is no test for the helper in question, and the fix is so minor and the bug occurs in such an edge case that I have deemed a catching test not worth my time at this point.  If someone else wanted to address this I have no issues with that.
> ADX-730 Hotfix for 500 error opening private dataset.

- ckanext/unaids/react/components/BulkFileUploaderComponent/index.test.js
- ckanext/unaids/react/components/BulkFileUploaderComponent/src/App.js
On my holiday I got thinking a bit about the partial filename matching logic as I would love this little feature to work.  Here's what I came up with.
We compare two file names, a and b,  to see if they match:
If a and b are equal, they match.
If a and b both open with the same three or more chars, and close with the same 3 or more chars, and has the same filename extension then we do a regex match on the middle non-matching part. This reg ex will only allow the middle non-matching parts of each filename to consist of the following inserted or swapped:
- a number
- a number or the word "copy" in parenthesis
- a number or the word "copy" after a hyphen
Providing that only one resource matches the new resource name following this logic we will propose the default action of overriding that …
> Adx 725 partial matching

- ckanext/unaids/validators.py
Very small change to ensure that the system is correctly guessing pjnz file types and thus assigning the correct resource icon. 
At the moment the bulk file uploader (and those using the api) may not include the "format" field when creating a resource.  In most cases ckan core will auto guess the format for you, but because pjnz is a fairly custom file type it is not guessed by default.  This changes corrects the matter in the same way that we previously made a change to correctly guess geojson data.
> ADX-739 Guess pjnz file types.

- ckanext/unaids/logic.py
- ckanext/unaids/tests/test_logic.py
- ckanext/unaids/theme/templates/scheming/form_snippets/upload.html
Problem: users have edited and saved metadata in less than the time it takes for the FileInputComponent to load.  This has meant that the giftless metadata, which is added to the form submission by the file input component, was lost. 
Possible solutions:
- Delay form submission until the file input component had properly loaded
- Ensure that the relevant information is supplied as part of the page HTML, so that the form can be used even if the FileInputComponent entirely fails to load.
I have pursued the second option, as this is how we are approaching the matter everywhere else in the CKAN UI; the HTML responsible for the giftless metadata that is created/updated by the FileInputComponent react code is now initialised by the server upon page load. I've used Chrome request throttling to …
> ADX-792 Default giftless metadata included at page load. 

- ckanext/unaids/actions.py
- ckanext/unaids/plugin.py
- ckanext/unaids/tests/test_actions.py
Adds a new API action that simply returns the current user obj.  Can be used to verify if an API key is valid. Tests included.
Is there a security concern around this endpoint?  Should we throttle the number of times someone can call it?
> ADX-279 Add API action user_show_me

- ckanext/unaids/theme/templates/home/layout1.html
A tiny change to enable UNAIDS to translate the instructional pages linked to from the home page.  I've carefully checked it all works locally.
> ADX-789 Link to portugese translations of instructional pages

- ckanext/unaids/theme/templates/snippets/search_form.html
- https://fjelltopp.atlassian.net/browse/ADX-614
- Fixed the `x` button on the filter pill having the wrong url
> ADX-614-fix-unfilter-url-2

- README.md
I have migrated all ADR translation docs into a single confluence page. This page includes both sections of readme from adx_develop and ckanext-unaids.
I think it makes sense to keep all of the knowledge in a single doc in our wiki.
> ADX-781 Migrated ADR translations docs to confluence

- ckanext/unaids/helpers.py
- ckanext/unaids/plugin.py
- ckanext/unaids/theme/templates/package/read_base.html
- [ADX-803-add-datasetid-to-navigator-url](https://fjelltopp.atlassian.net/browse/ADX-803)
- Update the link on the dataset_view page to include the dataset_id in the url so that users are redirected directly to the correct workflow within navigator
> ADX-803-add-datasetid-to-navigator-url

- ckanext/unaids/logic.py
- ckanext/unaids/plugin.py
- ckanext/unaids/tests/test_logic.py
1. We have a custom uploader which preserves original uploaded filenames as `url` column in resource db
2. the resource_dictize core ckan function is using ckan.lib.munge_filename to generate full urls for resources is solr visible with `resource_show`
I think the easiest fix for this is to leverage `IResourceController` and with `before_show` I can substitute the filename in resource_dict url with the value resource.url we store in the db.
The filename is still stripped from whitespaces and special characters by giftless but we're getting:
`CKAN Datasets & Resources.postman_collection` -> `CKANDatasetsResources.postman_collection.json`
which is quite alright in my opinion.
> ADX-622 case sensitive download links

- ckanext/unaids/assets/custom.css
- https://fjelltopp.atlassian.net/browse/ADX-811
- All css references with `url(` have also been manually checked in `custom.css` and `unaids.css`
- Only `sprite-resource-icons.png` was broken
> ADX-811-fix-broken-resource-sprites

- ckanext/unaids/theme/templates/home/layout1.html
- https://fjelltopp.atlassian.net/browse/ADX-813
- Made change as [html5 does not support `<center>` tags anymore](https://www.w3docs.com/learn-html/html-center-tag.html)
- Swapped out `<center>hello</center>` with `<div class="text-center">hello</div>`
- Also fixed bad use of `img-responsive` and bootstrap column sizing
> ADX-813-remove-deprecated-center-tags

- ckanext/unaids/actions.py
- ckanext/unaids/logic.py
- ckanext/unaids/plugin.py
- ckanext/unaids/tests/test_actions.py
- ckanext/unaids/tests/test_logic.py
- dev-requirements.txt
This PR introduces auto-population of data dictionaries from Frictionless Data table schemas used in data validation.
Current logic is to update the field's 'label' and 'description' in the data dictionary only if a corresponding field exists in the validation table schema and if no pre-existing label or description exists in the data dictionary for the field.
The logic fails silently if you try to auto-populate the data dictionary for a resource that has no associated table schema.  It will throw errors for all other failure cases.  In the "after_upload" hook we want complete silent failure though, since the task runs as a background. I have therefore decided to catch all exceptions and log them, but not block code execution, as this causes significant problems down stream. 
For …
> ADX-470 data dictionaries

- ckanext/unaids/theme/templates/base.html
The CSS was being loaded in the wrong place.  This was creating a flash of unformated website whilst the browser loaded stuff before the CSS files. This tiny PR just ensures the CSS is loaded in the head tag.
> ADX-815 Load CSS styles at the top of the page, not the bottom

- ckanext/unaids/logic.py
- ckanext/unaids/tests/test_logic.py
The ckanext-unaids filename generator was not handling non-ascii symbol.
I needed to get rid of non-ascii characters enterily due to CKAN not handling them even after upload (things like view controller etc. are erroring).
With the migration to python3 issues like this should get much easier.
> ADX-817 non-ascii filenames

- ckanext/unaids/theme/templates/base.html
Replace default CKAN styling, since we are loading UNAIDS styling. 
We are using super() for the styling block, but the only style this imports from core CKAN is the CKAN default CSS.
> ADX-815 Remove default CKAN css

- ckanext/unaids/blueprints/validate_user_profile.py
- ckanext/unaids/tests/test_blueprints.py
So, for future reference, I had used the following for registering my blueprint:
```python
validate_user_profile = Blueprint(
'validate_user_profile',
__name__,
)
```
and
```python
validate_user_profile.add_url_rule(
"/",
view_func=check_user_affiliation,
methods=['GET']
)
```
I had, incorrectly, presumed that without explicitly setting `prefix=` in the Blueprint constructor call that it would default to the blueprint name... I was wrong and so my `add_url_rule` was overwriting the `home.index` url.
This PR includes a general test to make sure we don't do this again with future blueprints (thanks @tomeksabala) and the fix.
Tested manually locally and passes integration tests.
> ADX-841 bug fix

- ckanext/unaids/react/components/FileInputComponent/src/ResourceForker.js
Depends upon https://github.com/fjelltopp/ckanext-fork/pull/12 being merged.
Some small changes to ensure the JS ResourceForker responds to these changes in resource_autocomplete endpoint.
> ADX-879 Select & mark resource if search query matches their id

- ckanext/unaids/assets/FileInputComponent.css
- ckanext/unaids/react/components/FileInputComponent/src/App.js
- ckanext/unaids/react/components/FileInputComponent/src/ResourceForker.js
We have moved markQuerySubstring from a per-search-word regex to a global OR regex - this prevents recursive updates, e.g. to prevent searchQuery="Poland A" adding `<mark>` tags around "Poland" and then a new mark tag around the "A" of `<mark>`.
I have also added a general error boundary to the component merging in the pre-existing FileUploader hard-coded-error-boundary-like-return.
TODO:
> ADX-891 Improve markQuerySubstring and add error boundary

- ckanext/unaids/theme/templates/user/edit_user_form.html
Minimal changes in the template **edit_user_form.html**, I added back 3 old passwords inputs but as hidden;
Did not use `form.input() `due to it adding a label tag before the input.
> Add hidden passwords field for CKAN to not crash when updating About text or upload a new Profile Picture
